// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/resume-analyzer": {
    params: {};
  };
  "/live-interview": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/architecture": {
    params: {};
  };
  "/health-check": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/ai-coach": {
    params: {};
  };
  "/analysis": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/careers": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/cookies": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/status": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/story": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forgot-password" | "/resume-analyzer" | "/live-interview" | "/notifications" | "/architecture" | "/health-check" | "/dashboard" | "/ai-coach" | "/analysis" | "/settings" | "/billing" | "/careers" | "/contact" | "/cookies" | "/history" | "/pricing" | "/privacy" | "/reports" | "/signup" | "/status" | "/about" | "/login" | "/story" | "/terms";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/resume-analyzer.tsx": {
    id: "routes/resume-analyzer";
    page: "/resume-analyzer";
  };
  "routes/live-interview.tsx": {
    id: "routes/live-interview";
    page: "/live-interview";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
  "routes/architecture.tsx": {
    id: "routes/architecture";
    page: "/architecture";
  };
  "routes/health-check.tsx": {
    id: "routes/health-check";
    page: "/health-check";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/ai-coach.tsx": {
    id: "routes/ai-coach";
    page: "/ai-coach";
  };
  "routes/analysis.tsx": {
    id: "routes/analysis";
    page: "/analysis";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/billing.tsx": {
    id: "routes/billing";
    page: "/billing";
  };
  "routes/careers.tsx": {
    id: "routes/careers";
    page: "/careers";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/cookies.tsx": {
    id: "routes/cookies";
    page: "/cookies";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/reports.tsx": {
    id: "routes/reports";
    page: "/reports";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/status.tsx": {
    id: "routes/status";
    page: "/status";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/story.tsx": {
    id: "routes/story";
    page: "/story";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/resume-analyzer": typeof import("./app/routes/resume-analyzer.tsx");
  "routes/live-interview": typeof import("./app/routes/live-interview.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
  "routes/architecture": typeof import("./app/routes/architecture.tsx");
  "routes/health-check": typeof import("./app/routes/health-check.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/ai-coach": typeof import("./app/routes/ai-coach.tsx");
  "routes/analysis": typeof import("./app/routes/analysis.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/billing": typeof import("./app/routes/billing.tsx");
  "routes/careers": typeof import("./app/routes/careers.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/cookies": typeof import("./app/routes/cookies.tsx");
  "routes/history": typeof import("./app/routes/history.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/reports": typeof import("./app/routes/reports.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/status": typeof import("./app/routes/status.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/story": typeof import("./app/routes/story.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
};